version: "3.1"

services:
  db:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=propctrl@postgres.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    
  app:
    build: .
    working_dir: /app/
    volumes:
      - .:/app/
    ports:
      - "80:80"